import json, os

base = 'd:/test1/devtools/public/locales/zh-CN'

files = {
    'base64.json': {"mode":"模式","modeEncode":"编码","modeDecode":"解码","inputLabel":"纯文本","inputLabelDecode":"Base64 字符串","outputLabel":"Base64 输出","outputLabelDecode":"解码文本","placeholderEncode":"输入要编码的文本...","placeholderDecode":"输入 Base64 字符串...","statusEncoded":"已编码","statusDecoded":"已解码","errorInvalid":"无效的 Base64 字符串"},
    'url-encode.json': {"mode":"模式","modeEncode":"编码","modeDecode":"解码","scope":"范围","scopeURI":"URI","scopeComponent":"组件","inputLabel":"原始 URL","outputLabel":"结果","placeholderEncode":"https://example.com/search?q=hello world","errorInvalid":"错误：无效的 URL 编码"},
    'uuid-generator.json': {"optionsLabel":"选项","versionLabel":"版本","countLabel":"数量","uppercaseLabel":"大写","noDashesLabel":"去除连字符","generatedCount":"已生成 {{count}} 个 UUID"},
    'html-escape.json': {"modeEscape":"转义","modeUnescape":"还原","inputLabel":"HTML / 文本","outputLabel":"转义后的 HTML","entitiesTitle":"常用 HTML 实体","colChar":"字符","colEntity":"实体","colCode":"代码"},
    'text-diff.json': {"modeChar":"字符","modeWord":"单词","modeLine":"行","modeLabel":"模式","originalLabel":"原文","modifiedLabel":"修改后","diffResultLabel":"差异结果","statsAdded":"+{{count}} 新增","statsRemoved":"-{{count}} 删除"},
    'markdown-preview.json': {"modeSplit":"分屏","modeEditor":"编辑器","modePreview":"预览","editorLabel":"Markdown","previewLabel":"预览","placeholder":"在此输入 Markdown..."},
    'yaml-json.json': {"modeYamlToJson":"YAML → JSON","modeJsonToYaml":"JSON → YAML","inputYaml":"YAML 输入","inputJson":"JSON 输入","outputJson":"JSON 输出","outputYaml":"YAML 输出","statusToJson":"✓ 已转换为 JSON","statusToYaml":"✓ 已转换为 YAML"},
    'code-formatter.json': {"indentLabel":"缩进","inputLabel":"输入代码","outputLabel":"输出","statusFormatted":"✓ 已格式化","statusMinified":"✓ 已压缩 ({{from}} → {{to}} 字符)"},
    'color-converter.json': {"openPicker":"打开取色器","hexLabel":"HEX","rgbLabel":"RGB","hslLabel":"HSL","redLabel":"红","greenLabel":"绿","blueLabel":"蓝","hueLabel":"色相 (0-360)","satLabel":"饱和度 (%)","lightLabel":"亮度 (%)"},
    'number-base.json': {"bitPattern":"位模式（8位分组）","errorInvalid":"无效的 {{label}} 数字"},
    'image-base64.json': {"dropLabel":"拖放图片到此处或点击上传","dropFormats":"PNG, JPG, GIF, WebP, SVG","base64Size":"{{size}} KB (Base64)","dataUriLabel":"Data URI","cssLabel":"CSS 背景","htmlLabel":"HTML img 标签","decodeTitle":"Base64 → 预览","decodePlaceholder":"粘贴 data URI 或原始 Base64..."},
    'hash-generator.json': {"inputLabel":"输入文本","inputPlaceholder":"输入要哈希的文本...","aboutTitle":"关于哈希函数","aboutText":"密码学哈希函数从输入数据生成固定大小的摘要。它们是单向的（不可逆）且确定性的。SHA-256 和 SHA-512 推荐用于安全敏感场景。MD5 和 SHA-1 在加密用途上已被认为不安全。"},
    'password-gen.json': {"optionsLabel":"选项","lengthLabel":"长度：{{n}}","countLabel":"数量","strengthLabel":"强度预览","charset":{"uppercase":"大写字母","lowercase":"小写字母","digits":"数字","symbols":"符号","excludeAmbiguous":"排除易混淆字符"},"strength":{"weak":"弱","fair":"一般","good":"良好","strong":"强"},"passwordCount":"{{count}} 个密码"},
    'number-format.json': {"placeholder":"输入数字...","labels":{"commaSeparated":"千位分隔","fixed2":"保留2位小数","scientific":"科学计数","percentage":"百分比","currencyUSD":"货币 (USD)","currencyCNY":"货币 (CNY)","chineseNormal":"中文 (普通)","chineseCapital":"中文 (大写)","binary":"二进制","hexadecimal":"十六进制","octal":"八进制","bytes":"字节大小"}},
    'http-status.json': {"searchPlaceholder":"搜索状态码...","filterAll":"全部","selectPrompt":"选择状态码查看详情","groups":{"1xx":"信息","2xx":"成功","3xx":"重定向","4xx":"客户端错误","5xx":"服务器错误"},"codes":{"100":{"phrase":"Continue","description":"服务器已收到请求头，客户端应继续发送请求体。"},"101":{"phrase":"Switching Protocols","description":"服务器正在切换协议。"},"103":{"phrase":"Early Hints","description":"在最终 HTTP 消息之前返回部分响应头。"},"200":{"phrase":"OK","description":"请求成功。"},"201":{"phrase":"Created","description":"请求已完成，新资源已创建。"},"202":{"phrase":"Accepted","description":"请求已被接受处理，但处理尚未完成。"},"204":{"phrase":"No Content","description":"服务器成功处理请求，但不返回任何内容。"},"206":{"phrase":"Partial Content","description":"服务器仅返回资源的一部分。"},"301":{"phrase":"Moved Permanently","description":"请求的资源已永久移到新 URL。"},"302":{"phrase":"Found","description":"请求的资源临时位于不同的 URL。"},"304":{"phrase":"Not Modified","description":"资源未被修改。"},"307":{"phrase":"Temporary Redirect","description":"临时重定向，方法不得改变。"},"308":{"phrase":"Permanent Redirect","description":"永久重定向，方法不得改变。"},"400":{"phrase":"Bad Request","description":"服务器无法处理请求，因为客户端错误。"},"401":{"phrase":"Unauthorized","description":"需要身份验证。"},"403":{"phrase":"Forbidden","description":"服务器理解请求但拒绝执行。"},"404":{"phrase":"Not Found","description":"找不到请求的资源。"},"405":{"phrase":"Method Not Allowed","description":"请求方法不被允许。"},"408":{"phrase":"Request Timeout","description":"服务器等待请求超时。"},"409":{"phrase":"Conflict","description":"请求与服务器当前状态冲突。"},"410":{"phrase":"Gone","description":"资源已永久不可用。"},"422":{"phrase":"Unprocessable Entity","description":"请求格式正确，但语义错误无法处理。"},"429":{"phrase":"Too Many Requests","description":"请求频率过高，触发限流。"},"500":{"phrase":"Internal Server Error","description":"服务器遇到意外情况，无法完成请求。"},"501":{"phrase":"Not Implemented","description":"服务器不支持完成请求所需的功能。"},"502":{"phrase":"Bad Gateway","description":"服务器从上游服务器收到无效响应。"},"503":{"phrase":"Service Unavailable","description":"服务器暂时无法处理请求。"},"504":{"phrase":"Gateway Timeout","description":"服务器未及时收到上游服务器的响应。"},"507":{"phrase":"Insufficient Storage","description":"服务器存储空间不足。"}}},
    'cron-parser.json': {"expressionLabel":"表达式","descriptionLabel":"说明","presetsLabel":"常用预设","fieldRefLabel":"字段参考","specialNote":"特殊：* (任意), , (列表), - (范围), / (步长)","presets":{"everyMinute":"每分钟","everyHour":"每小时","everyDayMidnight":"每天午夜","everyMondayNine":"每周一 9 点","firstOfMonth":"每月 1 日","everyWeekday":"每个工作日"},"fields":{"minute":"分钟","hour":"小时","dayOfMonth":"日","month":"月","dayOfWeek":"星期","minuteRange":"0-59","hourRange":"0-23","domRange":"1-31","monthRange":"1-12 (或 JAN-DEC)","dowRange":"0-7 (0 和 7 均为周日)"},"parse":{"invalid":"无效的 Cron 表达式（需要 5 个字段）","every":"每{{field}}","any":"任意{{field}}","everyN":"每 {{n}} 个{{field}}","everyNFrom":"从{{field}} {{start}} 开始每 {{n}} 个{{field}}","fromTo":"从{{field}} {{start}} 到{{field}} {{end}}","atList":"在{{field}} {{list}}","at":"在{{field}} {{value}}","inMonth":"{{month}}","onDay":"{{day}}"},"months":{"1":"1月","2":"2月","3":"3月","4":"4月","5":"5月","6":"6月","7":"7月","8":"8月","9":"9月","10":"10月","11":"11月","12":"12月"},"days":{"0":"周日","1":"周一","2":"周二","3":"周三","4":"周四","5":"周五","6":"周六"}},
    'timestamp.json': {"currentTime":"当前时间","live":"实时","paused":"已暂停","useThis":"使用此时间戳 →","tsToDate":"时间戳 → 日期","dateToTs":"日期 → 时间戳","placeholderTs":"Unix 时间戳 (如 1700000000)","iso8601":"ISO 8601","unixSeconds":"Unix (秒)","unixMs":"Unix (毫秒)"},
    'regex-tester.json': {"patternLabel":"正则表达式","patternPlaceholder":"输入正则表达式...","flagsLabel":"标志 (g, i, m, s)","testStringLabel":"测试字符串","testStringPlaceholder":"输入测试字符串...","replaceLabel":"替换","replacePlaceholder":"替换字符串（$1, $2 为分组）...","matchesLabel":"匹配结果","groupLabel":"分组 {{n}}","flags":{"global":"global","globalDesc":"查找所有匹配","ignoreCase":"ignore case","ignoreCaseDesc":"不区分大小写","multiline":"multiline","multilineDesc":"^ 和 $ 匹配行边界","dotAll":"dotAll","dotAllDesc":". 匹配换行符"}},
    'jwt-decoder.json': {"tokenLabel":"JWT Token","tokenPlaceholder":"粘贴 JWT Token...","tabHeader":"Header","tabPayload":"Payload","tabSignature":"Signature","loadSample":"加载示例","sigNote":"签名验证需要密钥，无法在客户端安全执行。","expired":"已过期 {{date}}","expires":"过期时间 {{date}}"},
}

for fname, data in files.items():
    fpath = os.path.join(base, fname)
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'Written: {fname}')

print('Done:', len(files), 'files')
